### ISSUE TITLE
Release version is "dev"

### ISSUE THREAD

**Issue by yochem** [wader/jq-lsp#35]
```
$ go install github.com/wader/jq-lsp@latest
$ go --version
dev
```

Although in the code it states:
https://github.com/wader/jq-lsp/blob/7bfb70db808e8dc38003ee29a1d6d8372f423b1d/main.go#L11-L12

The release build doesn't seem to set the version, but perhaps I'm not seeing something. I'm not really familiar with the Go tooling.

I think this might be the reason why Neovim doesn't automatically start the server? Here's the `:LpsInfo` output:

```
LSP configs active in this buffer (bufnr: 3) ~
- Language client log: ~/.local/state/nvim/lsp.log
- Detected filetype: `jq`
- 0 client(s) attached to this buffer
- Other clients that match the "jq" filetype:
- Config: jqls
  filetypes:         jq
  cmd:               ~/.local/share/go/bin/jq-lsp
  version:           `dev  jq-lsp - jq language server For details see https://github.com/wader/jq-ls…` (Failed to get version) Tried:
  `/Users/yochem/.local/share/go/bin/jq-lsp --version`
  `/Users/yochem/.local/share/go/bin/jq-lsp -version`
  `/Users/yochem/.local/share/go/bin/jq-lsp version`
  `/Users/yochem/.local/share/go/bin/jq-lsp --help`
  
  executable:        true
  autostart:         true
  root directory:    /private/tmp/
```

It looks like it tries to parse the version output, and probably expects some sort of semver version. But I have to investigate this a bit more.

**Comment by wader** [comment]
Hey, thanks for the bug report. No you are correct, it's broken. The current existing version stuff was suppose to be used when building release binaries but that never got finished. But hopefully it would not be too much work to get proper versions numbers when building from source from a tag somehow. Will have a look at it later today or in the week, feel free to poke around and open a PR if you feel motived.

What does neovim expect as version output from a lsp? just 1.2.3 or v1.2.3 etc?

**Comment by yochem** [comment]
It's both fine, the function that tries to find the version is defined here:

https://github.com/neovim/nvim-lspconfig/blob/5a812abc65d529ea7673059a348814c21d7f87ff/lua/lspconfig/health.lua#L59-L83

**Comment by wader** [comment]
Try now:
```sh
$ GOPROXY=direct go install github.com/wader/jq-lsp@latest
go: downloading github.com/wader/jq-lsp v0.1.10
$ $(go env GOPATH)/bin/jq-lsp --version
v0.1.10

**Comment by yochem** [comment]
```
LSP configs active in this buffer (bufnr: 1) ~
- Language client log: ~/.local/state/nvim/lsp.log
- Detected filetype: `jq`
- 1 client(s) attached to this buffer
- Client: `jqls` (id: 1, bufnr: [1])
  root directory:    /private/tmp/
  filetypes:         jq
  cmd:               ~/.local/share/go/bin/jq-lsp
  version:           `v0.1.10`
  executable:        true
  autostart:         true
```

Perfect! Thanks!

**Comment by wader** [comment]
🥳 btw is this something new in nvim-lspconfig?

**Comment by yochem** [comment]
Do you mean the output I showed here? They changed the `:LspInfo` command to be an alias of `:checkhealth lspconfig`, which follows the `checkhealth` convention they try to establish for plugins.

**Comment by wader** [comment]
Yes, that nvim-lspconfig can run command to figure out version. I was thinking why it haven't been noticed before but that might explain why then 👍
