### ISSUE TITLE
using $ENV variable raises 'not found' error

### ISSUE THREAD

**Issue by SijanC147** [wader/jq-lsp#4]

**Comment by wader** [comment]
Hey, thanks for the report, should be fixed in master now

**Comment by SijanC147** [comment]
yep, confirmed fixed! good job 👏  keep it up, jq is really underrated for what it's capable of, and and lsp is an awesome idea!

**Comment by wader** [comment]
Thanks 👍 yeap it's very capable and once you wrap your head around generator/backtracking it feels kind of normal :) glad to hear  jq-lsp is being useful! btw which editor/IDE do you use it with?

**Comment by SijanC147** [comment]
currently using it with vscode, as there is another [jq-playground](https://github.com/davidnussio/vscode-jq-playground) is another extension which i've found invaluable recently :)

**Comment by wader** [comment]
Nice, i should give it a try. Does it play well with [vscode-jq](https://github.com/wader/vscode-jq)? i thought about doing some kind of repl or eval feature for vscode-jq but didn't really come up with a nice interface, eval selection? own window? currently i usually run a `fq -i` in a terminal as a playground

**Comment by SijanC147** [comment]
i haven't tried it with vscode-jq yet, because i usually safe the "notebook" files with the extension `.jqpg`, but i do run vscode-jq with the module files i write, and it's been a great help there.

what would be cool is if this could somehow run inference on the input JSON while writing the query, and provide intellisense for specific attributes when writing the query itself.

**Comment by wader** [comment]
> i haven't tried it with vscode-jq yet, because i usually safe the "notebook" files with the extension `.jqpg`, but i do run vscode-jq with the module files i write, and it's been a great help there.

Aha i see

> what would be cool is if this could somehow run inference on the input JSON while writing the query, and provide intellisense for specific attributes when writing the query itself.

That would be cool, probably would involve some tricky query rewriting to do. fq has auto completion that is kind of a simplified rough version of that, but it works very well in practice. It works by taking the string from start to the current cursor position, does some heuristics about ending of the string, parse to AST to figure what kind of completion it is (function, variable, index), rewrites query to gets all keys, functions etc, eval it and filter to get suggestions.

The problem with this approach is that the string from start to cursor needs to be parseable as jq, so it wont work with brackets and parentheses and such (will be unbalanced). Have some ideas how one could make that work also but is not easy i guess.

If your curious it's implemented here https://github.com/wader/fq/blob/master/pkg/interp/repl.jq#L51 https://github.com/wader/fq/blob/master/pkg/interp/query.jq
