### ISSUE TITLE
Can't get module / imports to work

### ISSUE THREAD

**Issue by LeonB** [wader/jq-lsp#9]
``` jq
import "jq-lib" as L;

L::testfunction
```

gives the warning: `L::testfunction not found`

<img width="1888" alt="Screenshot 2023-06-12 at 10 16 33" src="https://github.com/wader/jq-lsp/assets/3979/ceb5e41e-d0a2-4698-8c49-d60d63c57c90">

Is there I way I can setup the directory to search modules from? Just like the `-L` option from the `gojq` cli?

**Comment by wader** [comment]
Hi, thanks for the report. Yeap that is missing at the moment, but i guess it shouldn't be that much work to fix.

About `-L`, that should be possible also but i'm not sure how it would be communicated to the lsp serve? thru extension option? some kind of config in jq file?

**Comment by wader** [comment]
Maybe create a separate issue for the search path thing?

**Comment by wader** [comment]
👍 and let me know if the PR fixed your problem

**Comment by LeonB** [comment]
Did fix the issue. Thanks!
